#! /bin/bash

set -eux

region=ap-southeast-2

## Install nginx

amazon-linux-extras enable nginx1
yum clean metadata
yum -y install nginx
yum -y install nginx-mod-stream

## Enable nginx during boot

systemctl enable nginx

## Set which port will be opened to receive incoming traffic

proxy_port=""

## Destination IP address

dest_ip=""

## Destination port - e.g: 1433 if you want to forward connections to a MSSQL server, or 5432 if postgres

dest_port=""

## Configure nginx vhost

mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf-bkp

envsubst < /tmp/nginx.tpl.conf > /etc/nginx/nginx.conf

systemctl restart nginx
